language: python
python:
- "3.5"
install:
- pip install -r requirements.txt
- cp ./settings_example.py ./lunchscraper/settings.py
- ls -Rl
- touch data/subscribers.json
- pip install .
#- python setup.py install
script:
- pytest tests/
